"""changed license num model length from 11 to 13 characters (includes dashes)

Revision ID: 2d54612ff75f
Revises: 8b6f70cb1406
Create Date: 2026-09-10 16:31:45.220930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d54612ff75f'
down_revision: Union[str, Sequence[str], None] = '8b6f70cb1406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'license_num',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'license_num',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
