"""Added new column in audit logs: action type

Revision ID: 8111d4ffb6d4
Revises: 968c3e45e794
Create Date: 2026-09-03 06:44:24.268899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8111d4ffb6d4'
down_revision: Union[str, Sequence[str], None] = '968c3e45e794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    audit_action_enum = postgresql.ENUM('create', 'update', 'suspend', 'resolve', 'delete', name='audit_action')
    audit_action_enum.create(op.get_bind())
    
    op.add_column('audit_logs', sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'SUSPEND', 'RESOLVE', 'DELETE', name='audit_action'), nullable=False))
    op.drop_constraint(op.f('incidents_resolved_by_fkey'), 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'accounts', ['resolved_by'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key(op.f('incidents_resolved_by_fkey'), 'incidents', 'users', ['resolved_by'], ['user_id'])
    op.drop_column('audit_logs', 'action')
    # ### end Alembic commands ###
