"""add account_code to accounts

Revision ID: 8b6f70cb1406
Revises: 8111d4ffb6d4
Create Date: 2026-09-08 18:42:13.672978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6f70cb1406'
down_revision: Union[str, Sequence[str], None] = '8111d4ffb6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_code', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['account_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'account_code')
    # ### end Alembic commands ###
