"""initial schema

Revision ID: 968c3e45e794
Revises: 
Create Date: 2026-08-30 22:14:08.979353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968c3e45e794'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='account_status'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DRIVER', name='account_role'), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('destinations',
    sa.Column('destination_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('destination_id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('SUSPENSION', 'WARNING', 'UPDATED', name='notification_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('terminals',
    sa.Column('terminal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('terminal_name', sa.String(length=50), nullable=False),
    sa.Column('min_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('min_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('max_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('max_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('terminal_id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('license_num', sa.String(length=11), nullable=False),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('contact_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_num')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('average_travel_duration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.destination_id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['terminals.terminal_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('body_color', sa.String(length=7), nullable=False),
    sa.Column('body_number', sa.String(length=10), nullable=False),
    sa.Column('plate_number', sa.String(length=7), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'OPERATIONAL', 'UNDER_MAINTENANCE', name='vehicle_condition'), nullable=False),
    sa.Column('activity_status', sa.Enum('ACTIVE', 'LOADING', 'ON_ROUTE', name='vehicle_activity_status'), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('registry_expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('body_number'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('broadcast_notifications',
    sa.Column('broadcast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('broadcast_type', sa.Enum('PASSENGER_QUEUE', 'INCIDENT', name='broadcast_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.terminal_id'], ),
    sa.PrimaryKeyConstraint('broadcast_id')
    )
    op.create_table('dispatch_logs',
    sa.Column('dispatch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['accounts.account_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('dispatch_id')
    )
    op.create_table('geofence_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ENTER', 'EXIT', name='geofence_event_type'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.terminal_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OUTGOING', 'RETURNING', 'COMPLETED', name='trip_status'), nullable=False),
    sa.Column('time_departed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_arrived', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trip_duration_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('average_speed_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch_logs.dispatch_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('gps_logs',
    sa.Column('gps_log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('gps_log_id')
    )
    op.create_table('incidents',
    sa.Column('incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.Enum('VEHICLE_BREAKDOWN', 'FLOODED_ROAD', 'CRIME_INCIDENT', 'ROAD_ACCIDENT', name='incident_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', name='incident_status'), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reported_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('gps_logs')
    op.drop_table('trips')
    op.drop_table('geofence_events')
    op.drop_table('dispatch_logs')
    op.drop_table('broadcast_notifications')
    op.drop_table('vehicles')
    op.drop_table('routes')
    op.drop_table('users')
    op.drop_table('terminals')
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_table('destinations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
