"""vehicle plate length changed from 7 to 8 characters

Revision ID: 97309e234450
Revises: 2d54612ff75f
Create Date: 2026-09-12 15:52:21.789219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97309e234450'
down_revision: Union[str, Sequence[str], None] = '2d54612ff75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'plate_number',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'plate_number',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
