import { useState } from "react";
import { Link } from "react-router-dom";
import { Mail, CircleCheck, CircleX } from "lucide-react";
import { requestPasswordReset } from "../../api/authAPI";

export default function ForgotPassword() {
  const [email, setEmail] = useState(""); const [error, setError] = useState(null); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(null); setSending(true); try { await requestPasswordReset(email); setSent(true); } catch (err) { setError(err.message || "Could not request a reset link."); } finally { setSending(false); } };
  return <main className="flex min-h-screen w-screen items-center justify-center bg-[#042F2E] px-4"><section className="w-full max-w-[457px] rounded-[10px] bg-[#134E4A] px-[46px] py-[32px]"><h1 className="text-xl font-semibold text-[#eafff5]">Forgot password?</h1><div className="mt-1 h-[2px] w-[60px] bg-[var(--labels)]" />{sent ? <div className="mt-6 text-center"><CircleCheck className="mx-auto h-10 w-10 text-[#5DCAA5]" /><p className="mt-3 text-sm text-[#eafff5]">Check your email for a password-reset link.</p><p className="mt-2 text-xs text-[#9fcabd]">If the email matches an account, the link arrives shortly and expires in 30 minutes.</p></div> : <form onSubmit={submit} className="mt-6 space-y-4"><p className="text-sm text-[#9fcabd]">Enter your administrator email to receive a password-reset link.</p>{error && <p className="flex items-center gap-2 text-xs text-[#D98B72]" role="alert"><CircleX className="h-4 w-4" />{error}</p>}<label className="block text-xs text-[var(--labels)]">Email address<span className="relative mt-1.5 block"><Mail className="absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-[#22D3EE]" /><input type="email" required autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Enter your email" className="w-full rounded-[var(--input-radius)] border border-[var(--stroke-color)] bg-[var(--btn-fg)] px-10 py-3 text-sm text-[#eafff5] outline-none focus:border-[var(--stroke-color-focus)]" /></span></label><button type="submit" disabled={sending} className="h-[46px] w-full rounded-[5px] bg-[var(--labels)] text-sm font-semibold text-[var(--btn-fg)] disabled:opacity-50">{sending ? "Sending..." : "Send reset link"}</button></form>}<Link to="/login" className="mt-6 block text-center text-xs text-[var(--labels)] hover:underline">Back to sign in</Link></section></main>;
}
