import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { CheckCheck, CircleX, Eye, EyeClosed } from "lucide-react";
import { resetPassword } from "../../api/authAPI";

const PASSWORD_PATTERN = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/;
const PASSWORD_REQUIREMENT = "Use at least 8 characters, including uppercase and lowercase letters and a number.";

export default function ResetPassword() {
  const [params] = useSearchParams();
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [showPasswords, setShowPasswords] = useState(false); const [error, setError] = useState(null); const [saving, setSaving] = useState(false); const [complete, setComplete] = useState(false);
  const matches = password.length > 0 && password === confirmation;
  const submit = async (event) => { event.preventDefault(); setError(null); if (!params.get("token")) return setError("This reset link is invalid or incomplete."); if (!PASSWORD_PATTERN.test(password)) return setError(PASSWORD_REQUIREMENT); if (!matches) return setError("New password and confirmation do not match."); setSaving(true); try { await resetPassword(params.get("token"), password, confirmation); setComplete(true); } catch (err) { setError(err.message || "Could not reset your password. Request a new link and try again."); } finally { setSaving(false); } };
  return <main className="flex min-h-screen w-screen items-center justify-center bg-[#042F2E] px-4"><section className="w-full max-w-[457px] rounded-[10px] bg-[#134E4A] px-[46px] py-[32px]"><h1 className="text-xl font-semibold text-[#eafff5]">Set a new password</h1><div className="mt-1 h-[2px] w-[60px] bg-[var(--labels)]" />{complete ? <div className="mt-6 text-center"><CheckCheck className="mx-auto h-10 w-10 text-[#5DCAA5]" /><p className="mt-3 text-sm text-[#eafff5]">Your password has been reset.</p><Link to="/login" className="mt-4 inline-block text-xs text-[var(--labels)] hover:underline">Sign in with your new password</Link></div> : <form onSubmit={submit} className="mt-6 space-y-4"><p className="text-sm text-[#9fcabd]">{PASSWORD_REQUIREMENT}</p>{error && <p className="flex items-center gap-2 text-xs text-[#D98B72]" role="alert"><CircleX className="h-4 w-4 shrink-0" />{error}</p>}<label className="block text-xs text-[var(--labels)]">New password<input type={showPasswords ? "text" : "password"} required value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1.5 w-full rounded-[var(--input-radius)] border border-[var(--stroke-color)] bg-[var(--btn-fg)] px-4 py-3 text-sm text-[#eafff5] outline-none focus:border-[var(--stroke-color-focus)]" /></label><label className="block text-xs text-[var(--labels)]">Confirm new password<span className="relative mt-1.5 block"><input type={showPasswords ? "text" : "password"} required value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="w-full rounded-[var(--input-radius)] border border-[var(--stroke-color)] bg-[var(--btn-fg)] px-4 py-3 pr-11 text-sm text-[#eafff5] outline-none focus:border-[var(--stroke-color-focus)]" /><button type="button" onClick={() => setShowPasswords((visible) => !visible)} aria-label={showPasswords ? "Hide passwords" : "Show passwords"} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#22D3EE] hover:text-[#eafff5]">{showPasswords ? <EyeClosed className="h-[18px] w-[18px]" /> : <Eye className="h-[18px] w-[18px]" />}</button></span></label>{matches && <p className="flex items-center gap-2 text-xs text-[#5DCAA5]"><CheckCheck className="h-4 w-4" />Passwords match</p>}<button type="submit" disabled={saving} className="h-[46px] w-full rounded-[5px] bg-[var(--labels)] text-sm font-semibold text-[var(--btn-fg)] disabled:opacity-50">{saving ? "Saving..." : "Reset password"}</button></form>}</section></main>;
}
