import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { changePassword } from '@/api/profileAPI';

export default function ChangePasswordScreen() {
  const router = useRouter(); const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [saving, setSaving] = useState(false); const dirty = Boolean(current || next || confirm);
  const leave = () => { if (dirty) Alert.alert('Exit Change Password?', 'All changes will be deleted.', [{ text: 'Continue editing', style: 'cancel' }, { text: 'Exit', style: 'destructive', onPress: () => router.back() }]); else router.back(); };
  const save = async () => { if (next !== confirm) return Alert.alert('Passwords do not match.'); setSaving(true); try { await changePassword(current, next, confirm); Alert.alert('Password updated', 'Please sign in again with your new password.', [{ text: 'OK', onPress: () => router.back() }]); } catch (error: any) { Alert.alert('Unable to update password', error?.response?.data?.detail ?? 'Please check your current password and try again.'); } finally { setSaving(false); } };
  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Pressable style={styles.back} onPress={leave}><Ionicons name="arrow-back" size={21} color="#E9FFFB" /><Text style={styles.title}>Change Password</Text></Pressable><Text style={styles.sub}>For your security, choose a password you haven’t used before.</Text><Field label="Current password" value={current} onChangeText={setCurrent} /><Field label="New password" value={next} onChangeText={setNext} /><Field label="Confirm new password" value={confirm} onChangeText={setConfirm} /><Text style={[styles.match, next && confirm && next !== confirm && styles.noMatch]}>{next && confirm && next === confirm ? '✓ Passwords match' : next && confirm ? 'Passwords do not match' : ''}</Text><Pressable disabled={saving} onPress={() => void save()} style={styles.save}><Text style={styles.saveText}>{saving ? 'Updating…' : 'Update Password'}</Text></Pressable></ScrollView></SafeAreaView>;
}
function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { const [show, setShow] = useState(false); return <View style={styles.fieldWrap}><Text style={styles.fieldLabel}>{label}</Text><View style={styles.fieldRow}><TextInput value={value} onChangeText={onChangeText} secureTextEntry={!show} style={styles.field} /><Pressable onPress={() => setShow(!show)}><Ionicons name={show ? 'eye-off-outline' : 'eye-outline'} size={16} color="#74A79F" /></Pressable></View></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#002B28' }, content: { flexGrow: 1, padding: 20 }, back: { flexDirection: 'row', alignItems: 'center', gap: 9 }, title: { color: '#FFF', fontSize: 16, fontWeight: '700' }, sub: { color: '#67C7BC', fontSize: 10, marginTop: 8, maxWidth: 255 }, fieldWrap: { marginTop: 19 }, fieldLabel: { color: '#71C9BF', fontSize: 9, letterSpacing: 2, marginBottom: 4 }, fieldRow: { height: 36, borderRadius: 8, borderColor: '#257C74', borderWidth: 1, backgroundColor: '#124C48', flexDirection: 'row', alignItems: 'center', paddingRight: 10 }, field: { flex: 1, color: '#FFF', paddingHorizontal: 10, fontSize: 12 }, match: { color: '#64E8A1', fontSize: 9, marginTop: 14 }, noMatch: { color: '#FFAD8D' }, save: { height: 45, borderRadius: 7, backgroundColor: '#1CAB8B', alignItems: 'center', justifyContent: 'center', marginTop: 'auto' }, saveText: { color: '#002D2A', fontWeight: '800' } });
